/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cuentahogar;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fernando
 */
public class VentanaInicial extends javax.swing.JFrame {

    private String bbdd;
    private String user;
    private String pass;
    ElementosDinamicos ed = new ElementosDinamicos();

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        //Tomamos la dimension de la pantalla para centrar las ventanasos
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        //Dimensionamos  y situamos ventana Principal, controlamos el cierre e incializamos
        this.setLocation(d.width / 2 - (d.width / 6) / 2, d.height / 2 - ((d.height / 3)) / 2);
        //iniciar componentes
        initComponents();
    }

    private boolean comprobarConexion(String bbdd, String user, String pass) {
        try {
            Connection link = null;
            Class.forName("org.gjt.mm.mysql.Driver");
            link = DriverManager.getConnection("jdbc:mysql://localhost/" + bbdd, user, pass);
            return true;
        } catch (Exception ex) {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etCuentaHogar = new javax.swing.JLabel();
        chkVolverMostrar = new javax.swing.JCheckBox();
        txtPass = new javax.swing.JPasswordField();
        txtBBDD = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        etBBDD = new javax.swing.JLabel();
        etUsr = new javax.swing.JLabel();
        etPass = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONFIGURACION");
        setResizable(false);

        etCuentaHogar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        etCuentaHogar.setText("CUENTA HOGAR");

        chkVolverMostrar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        chkVolverMostrar.setSelected(true);
        chkVolverMostrar.setText("Volver a mostrar al inicio");
        chkVolverMostrar.setToolTipText("");

        etBBDD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        etBBDD.setText("Nombre BBDD");

        etUsr.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        etUsr.setText("Usuario");

        etPass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        etPass.setText("Contraseña");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkVolverMostrar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etBBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etPass, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBBDD)
                                    .addComponent(txtPass)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(etCuentaHogar)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etCuentaHogar)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(etBBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(etUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkVolverMostrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            if (chkVolverMostrar.isSelected()) {
                ed.borrarFicheroIni();
            }
        } catch (Exception ex) {
            Logger.getLogger(VentanaInicial.class.getName()).log(Level.SEVERE, null, ex);
            ed.mostrarError("Fallo al gestionar el fichero \"cuentaHogar.ini\"", ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        if (!txtBBDD.getText().isEmpty() && !txtUser.getText().isEmpty() && txtPass.getPassword() != null) {
            HashMap<String, String> ficheroIni = new HashMap<String, String>();

            this.bbdd = txtBBDD.getText();
            this.user = txtUser.getText();
            this.pass = new String(txtPass.getPassword());

            if (this.comprobarConexion(bbdd, user, pass)) {

                try {
                    if (!chkVolverMostrar.isSelected()) {
                        ficheroIni = ed.crearFicheroIni(bbdd, user, pass, "no");
                    } else {
                        ed.borrarFicheroIni();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(VentanaInicial.class.getName()).log(Level.SEVERE, null, ex);
                    ed.mostrarError("Fallo al gestionar el fichero \"cuentaHogar.ini\"", ex);
                }

                ElementosGraficos eg = new ElementosGraficos(bbdd, user, pass);
                eg.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Imposible conectar con la BBDD", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Existe campos vacios", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkVolverMostrar;
    private javax.swing.JLabel etBBDD;
    private javax.swing.JLabel etCuentaHogar;
    private javax.swing.JLabel etPass;
    private javax.swing.JLabel etUsr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBBDD;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
